import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { useLocalCart } from "../modules/cart/hooks/useLocalCart";
import { UnauthenticatedCartDrawer } from "../modules/cart/UnauthenticatedCartDrawer";
import { MainLayout } from "../modules/layout/MainLayout";
import {
  getProducts,
  useProducts,
} from "../modules/products/api/get-products.api";
import { Product } from "../modules/products/product.model";
import { ProductsList } from "../modules/products/ProductsList";

type HomeProps = { products: Product[] };

const Home: NextPage<HomeProps> = ({ products }) => {
  const { data } = useProducts({ initialData: products });
  const { addProductToLocalCart } = useLocalCart();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <ProductsList
          products={data}
          onAddProductToCart={addProductToLocalCart}
        />
      </MainLayout>
      <UnauthenticatedCartDrawer />
    </>
  );
};

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
  const products = await getProducts();
  return { props: { products } };
};

export default Home;
